export type ShiftResultType = {
  ppA: number;
  ppB: number;
  ppC: number;
  pp: number;
  subTotal: number;
  charged: number;
  total: number;
  credit: number;
  creditSurcharge: number;
  creditPaid: number;
  cashPaid: number;
  discount: number;
  c_ms: number;
  c_fs: number;
  c_my: number;
  c_fy: number;
  c_mm: number;
  c_fm: number;
  tables: number;
};
